version: '3.8'

services:
  echoji-frontend:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npx vite preview --host 0.0.0.0 --port 8888